### ISSUE TITLE
Not working in tmux

### ISSUE THREAD

**Issue by lukewang1024** [sindresorhus/clipboard-cli#3]
When running inside tmux it will throw error. Seems like it is the underlying clipboardy that does not handle tmux environment well.

```
    at Function.module.exports.sync (clipboard-cli/node_modules/execa/index.js:277:26)
    at Object.pasteSync (clipboard-cli/node_modules/clipboardy/lib/macos.js:10:27)
    at Object.exports.readSync (clipboard-cli/node_modules/clipboardy/index.js:41:37)
    at Object.<anonymous> (clipboard-cli/cli.js:15:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by sindresorhus** [comment]
Can you include the actual error?

**Comment by lukewang1024** [comment]
It turns out to be a tmux config issue. `default-command` is accidentally set in my config to `/bin/zsh` so `tmux-sensible` won't get it wrapped with "reattach-to-user-namespace". Closing it. Thanks.
